<a href="https://colab.research.google.com/github/rmbgatram/c-repo/blob/main/numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy Examples**

**Creating 0D ndarray**

In [ ]:
import numpy as np
a = np.array(10)
print('0D Array elements: ', a)
print('Dimension of a: ', a.ndim)
print('size of a: ', a.size)
print(type(a))

0D Array elements:  10
Dimension of a:  0
size of a:  1
<class 'numpy.ndarray'>


**Creating 1D ndarray & accessing individual elements**
* a[index]
* starting index is 0
* -ve index gives elements from end

In [ ]:
import numpy as np
# Creating array using list
a = np.array([1, 2, 3, 4, 5]) 
# Creating array using tuple
b = np.array((1, 2, 3, 4, 5, 6)) 
# Prints Dimesion of a and b
print('Dimension of a: ', a.ndim)
print('Dimension of b: ', b.ndim)
# Prints size of a and b
print('Size of a: ', a.size)
print('Size of b: ', b.size)
# Prints Elements of a and b
print('1D Array Elements of a: ', a)
print('1D Array Elements of b: ', b)
# individual elements are accessed with index, index starts from 0
# negative index to access elements from the end
print('2nd Element of a: ', a[1]) 
print('3rd Element of b: ', b[2]) 
print('2nd Element of b from end: ', b[-2]) 


Dimension of a:  1
Dimension of b:  1
Size of a:  5
Size of b:  6
1D Array Elements of a:  [1 2 3 4 5]
1D Array Elements of b:  [1 2 3 4 5 6]
2nd Element of a:  2
3rd Element of b:  3
2nd Element of b from end:  5


**Creating 2D ndarray & accessing individual elements**
* a[rindex, cindex]
* starting index is 0
* -ve index gives elements from end

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('Dimension of a: ', a.ndim)
print('Size of a: ', a.size)
print('2D Array Elements: ', a)
print('a[1,1] Element: ', a[1,1])

Dimension of a:  2
Size of a:  6
2D Array Elements:  [[1 2 3]
 [4 5 6]]
a[1,1] Element:  5


**Creating 3D ndarray & accessing individual elements**

In [ ]:
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('3D Array Elements: ', a)
print('Dimension of a: ', a.ndim)
# first index signifies which matrix, second index signifies which array and third index signifies which element.
print('a[0,1,2] Element: ', a[0,1,2])

3D Array Elements:  [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension of a:  3
a[0,1,2] Element:  6


**Array Slicing**


*   a[start: end]
*   a[start: end: step]
* If we don't pass start its considered 0
* If we don't pass end its considered length of array in that dimension
* If we don't pass step its considered 1


In [8]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Elements from 2 to 5: ', a[1:5])
print('Elements from start to 4: ', a[:4])
print('Elements from 2 to end: ', a[2:])
print('Elements from start to end with step 2: ', a[::2])

Elements from 2 to 5:  [2 3 4 5]
Elements from start to 4:  [1 2 3 4]
Elements from 2 to end:  [ 3  4  5  6  7  8  9 10]
Elements from start to end with step 2:  [1 3 5 7 9]
